/*
 * This source file was generated by the Gradle 'init' task
 */
package kafka;

import kafka.player.AppProducerPlayer;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        AppProducerPlayer classUnderTest = new AppProducerPlayer();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
