/*
 * This source file was generated by the Gradle 'init' task
 */

package kafka.game;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.util.List;
import kafka.util.CommonKafka;
import kafka.util.KafkaConstants;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

public class AppProducerGame {
  public static void main(String[] args) {

    Producer<String, String> producer = CommonKafka.getProducer();
    ObjectMapper objectMapper = new ObjectMapper();

    Parser parser=new Parser();
    List<CommonGame> games= parser.parseDir(new File("data/twic1997"));
    System.out.println("games "+games.size());
    long id=1L;
    for (CommonGame game : games) {

      game.setId(id++);
      // envoyer au productuer

      try {
        String gameJson = objectMapper.writeValueAsString(game);
        ProducerRecord<String, String> record = new ProducerRecord<>(KafkaConstants.TOPIC_GAME, null, gameJson);

        producer.send(record);
        producer.flush();

      } catch (JsonProcessingException e) {
        e.printStackTrace(); // Gestion de l'erreur en cas de problème de conversion
      }
    }
    System.out.println("db insert games done "+games.size());





  }

}
