/*
 * This source file was generated by the Gradle 'init' task
 */

package kafka.game;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.util.List;
import java.util.Properties;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;
public class AppProducerGame {
  public static void main(String[] args) {

    Properties properties = new Properties();
    properties.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
    properties.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
    properties.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);

    Producer<String, String> producer = new KafkaProducer<>(properties);
    ObjectMapper objectMapper = new ObjectMapper();

    Parser parser=new Parser();
    List<CommonGame> games= parser.parseDir(new File("data/twic1997"));
    System.out.println("games "+games.size());
    long id=1L;
    for (CommonGame game : games) {

      game.setId(id++);
      // envoyer au productuer

      try {
        String gameJson = objectMapper.writeValueAsString(game);
        System.out.println(gameJson); // Affiche l'objet Game en JSON


        ProducerRecord<String, String> record = new ProducerRecord<>("topic-game2", null, gameJson);

        producer.send(record);
        producer.flush();

      } catch (JsonProcessingException e) {
        e.printStackTrace(); // Gestion de l'erreur en cas de problème de conversion
      }
    }
    System.out.println("db insert games done "+games.size());





  }

}
